"""initial schema

Revision ID: 2bc351640e80
Revises: 
Create Date: 2026-08-11 01:56:46.910631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2bc351640e80'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('plural', sa.String(length=80), nullable=False),
    sa.Column('hint', sa.String(length=160), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professions_key'), 'professions', ['key'], unique=True)
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('owner', 'caller', name='staff_role'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_email'), 'staff', ['email'], unique=True)
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('imported_by_id', sa.Integer(), nullable=True),
    sa.Column('rows_seen', sa.Integer(), nullable=False),
    sa.Column('rows_added', sa.Integer(), nullable=False),
    sa.Column('rows_skipped', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['imported_by_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professionals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=True),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('profession_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('stage', sa.Enum('imported', 'contacted', 'details_collected', 'signature_sent', 'signed', 'declined', 'not_valid', name='pipeline_stage'), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('called_by_id', sa.Integer(), nullable=True),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('specialties', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('languages', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('years', sa.Integer(), nullable=True),
    sa.Column('license', sa.String(length=120), nullable=True),
    sa.Column('vat_number', sa.String(length=60), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_year', sa.Integer(), nullable=True),
    sa.Column('subrole', sa.String(length=160), nullable=True),
    sa.Column('coverage', sa.String(length=160), nullable=True),
    sa.Column('cost_note', sa.Text(), nullable=True),
    sa.Column('costs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('faq', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['called_by_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['profession_id'], ['professions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professionals_assigned_to_id'), 'professionals', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_professionals_batch_id'), 'professionals', ['batch_id'], unique=False)
    op.create_index(op.f('ix_professionals_city'), 'professionals', ['city'], unique=False)
    op.create_index(op.f('ix_professionals_phone'), 'professionals', ['phone'], unique=False)
    op.create_index(op.f('ix_professionals_profession_id'), 'professionals', ['profession_id'], unique=False)
    op.create_index(op.f('ix_professionals_published'), 'professionals', ['published'], unique=False)
    op.create_index(op.f('ix_professionals_region'), 'professionals', ['region'], unique=False)
    op.create_index(op.f('ix_professionals_slug'), 'professionals', ['slug'], unique=True)
    op.create_index(op.f('ix_professionals_stage'), 'professionals', ['stage'], unique=False)
    op.create_table('agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('terms_version', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_name', sa.String(length=160), nullable=True),
    sa.Column('signature_svg', sa.Text(), nullable=True),
    sa.Column('signed_ip', sa.String(length=64), nullable=True),
    sa.Column('signed_user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agreements_professional_id'), 'agreements', ['professional_id'], unique=False)
    op.create_index(op.f('ix_agreements_token'), 'agreements', ['token'], unique=True)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=True),
    sa.Column('professional_name', sa.String(length=200), nullable=True),
    sa.Column('professional_role', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('buyer_name', sa.String(length=160), nullable=False),
    sa.Column('buyer_phone', sa.String(length=60), nullable=False),
    sa.Column('buyer_email', sa.String(length=255), nullable=True),
    sa.Column('best_time', sa.String(length=80), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('source_page', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('new', 'contacted', 'closed', 'lost', name='lead_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('callback_due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_callback_due'), 'leads', ['callback_due'], unique=False)
    op.create_index(op.f('ix_leads_created_at'), 'leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_leads_professional_id'), 'leads', ['professional_id'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('context', sa.String(length=160), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_professional_id'), 'reviews', ['professional_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_label', sa.String(length=160), nullable=True),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_kind'), 'events', ['kind'], unique=False)
    op.create_index(op.f('ix_events_lead_id'), 'events', ['lead_id'], unique=False)
    op.create_index(op.f('ix_events_professional_id'), 'events', ['professional_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_professional_id'), table_name='events')
    op.drop_index(op.f('ix_events_lead_id'), table_name='events')
    op.drop_index(op.f('ix_events_kind'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_reviews_professional_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_professional_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_created_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_callback_due'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_agreements_token'), table_name='agreements')
    op.drop_index(op.f('ix_agreements_professional_id'), table_name='agreements')
    op.drop_table('agreements')
    op.drop_index(op.f('ix_professionals_stage'), table_name='professionals')
    op.drop_index(op.f('ix_professionals_slug'), table_name='professionals')
    op.drop_index(op.f('ix_professionals_region'), table_name='professionals')
    op.drop_index(op.f('ix_professionals_published'), table_name='professionals')
    op.drop_index(op.f('ix_professionals_profession_id'), table_name='professionals')
    op.drop_index(op.f('ix_professionals_phone'), table_name='professionals')
    op.drop_index(op.f('ix_professionals_city'), table_name='professionals')
    op.drop_index(op.f('ix_professionals_batch_id'), table_name='professionals')
    op.drop_index(op.f('ix_professionals_assigned_to_id'), table_name='professionals')
    op.drop_table('professionals')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_staff_email'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_professions_key'), table_name='professions')
    op.drop_table('professions')
    # ### end Alembic commands ###
    # Alembic drops the tables but leaves the enum types behind, so a second
    # `upgrade head` after a rollback dies with "type staff_role already
    # exists". A migration you cannot re-apply is a trap during a deploy
    # rollback, so the types go too.
    op.execute("DROP TYPE IF EXISTS pipeline_stage")
    op.execute("DROP TYPE IF EXISTS lead_status")
    op.execute("DROP TYPE IF EXISTS staff_role")
